import type { Exercise } from "@/types";

const make = (
  id: string,
  name: string,
  description: string,
  primaryMuscle: Exercise["primaryMuscle"],
  secondaryMuscles: Exercise["secondaryMuscles"],
  type: Exercise["type"],
): Exercise => ({ id, name, description, primaryMuscle, secondaryMuscles, type });

export const EXERCISES: Exercise[] = [
  // CHEST
  make("chest-1", "Press de banca plano", "Empuje horizontal con barra en banco plano. El movimiento maestro del pecho.", "chest", ["triceps", "shoulders"], "barbell"),
  make("chest-2", "Press inclinado con barra", "Press en banco a 30-45° para enfatizar pecho superior.", "chest", ["shoulders", "triceps"], "barbell"),
  make("chest-3", "Press declinado con barra", "Banco declinado para aislar pecho inferior.", "chest", ["triceps"], "barbell"),
  make("chest-4", "Press con mancuernas plano", "Mayor rango de movimiento que la barra. Trabaja estabilizadores.", "chest", ["triceps", "shoulders"], "dumbbell"),
  make("chest-5", "Press inclinado con mancuernas", "Pecho superior con mayor estiramiento.", "chest", ["shoulders", "triceps"], "dumbbell"),
  make("chest-6", "Aperturas con mancuernas", "Movimiento de aislamiento. Estira el pectoral en la fase excéntrica.", "chest", ["shoulders"], "dumbbell"),
  make("chest-7", "Aperturas en máquina (peck deck)", "Aislamiento de pecho con tensión constante.", "chest", [], "machine"),
  make("chest-8", "Crossover en polea alta", "Aductión de brazos en polea. Tensión continua en el pectoral.", "chest", ["shoulders"], "cable"),
  make("chest-9", "Cable crossover bajo", "Polea baja a alta. Enfatiza pecho superior.", "chest", ["shoulders"], "cable"),
  make("chest-10", "Fondos en paralelas", "Peso corporal. Inclinarse hacia adelante para enfatizar pecho.", "chest", ["triceps", "shoulders"], "bodyweight"),
  make("chest-11", "Flexiones (push-ups)", "Ejercicio fundamental de empuje con peso corporal.", "chest", ["triceps", "shoulders"], "bodyweight"),
  make("chest-12", "Press en máquina", "Patrón de press guiado. Excelente para volumen seguro.", "chest", ["triceps"], "machine"),
  make("chest-13", "Pullover con mancuerna", "Trabaja pecho y dorsal en una expansión torácica.", "chest", ["back"], "dumbbell"),
  make("chest-14", "Press inclinado en Smith", "Movimiento guiado. Permite cargar más peso de forma segura.", "chest", ["shoulders", "triceps"], "machine"),
  make("chest-15", "Flyes con cables (en banco)", "Aperturas tumbado en banco con poleas para tensión continua.", "chest", ["shoulders"], "cable"),
  make("chest-16", "Press declinado con mancuernas", "Banco declinado con mancuernas. Énfasis en pecho inferior.", "chest", ["triceps"], "dumbbell"),
  make("chest-17", "Press inclinado en máquina", "Press guiado a 30-45°. Pecho superior con estabilidad.", "chest", ["shoulders", "triceps"], "machine"),
  make("chest-18", "Press de pecho en polea", "De pie con poleas. Tensión constante y trabajo de core.", "chest", ["shoulders", "triceps"], "cable"),
  make("chest-19", "Flexiones con pies elevados", "Pies sobre un banco. Mayor carga en pecho superior.", "chest", ["shoulders", "triceps"], "bodyweight"),
  make("chest-20", "Press en suelo con mancuernas", "Tumbado en el suelo. Recorrido corto, cuida los hombros.", "chest", ["triceps", "shoulders"], "dumbbell"),
  make("chest-21", "Press landmine a una mano", "Empuje diagonal con barra anclada. Pecho superior y estabilidad.", "chest", ["shoulders", "triceps"], "barbell"),

  // BACK
  make("back-1", "Dominadas (pull-ups)", "Tracción vertical con peso corporal. Rey del dorsal.", "back", ["biceps", "forearms"], "bodyweight"),
  make("back-2", "Jalón al pecho en polea", "Sustituto de dominadas guiado. Excelente para el dorsal ancho.", "back", ["biceps"], "cable"),
  make("back-3", "Remo con barra", "Tracción horizontal masiva para densidad de espalda.", "back", ["biceps", "forearms"], "barbell"),
  make("back-4", "Remo con mancuerna a una mano", "Aislamiento unilateral del dorsal.", "back", ["biceps"], "dumbbell"),
  make("back-5", "Remo en máquina (T-bar)", "Tracción horizontal estable. Mucha carga posible.", "back", ["biceps"], "machine"),
  make("back-6", "Remo en polea baja sentado", "Tracción horizontal con cable. Tensión constante.", "back", ["biceps"], "cable"),
  make("back-7", "Peso muerto convencional", "Levantamiento total. Trabaja toda la cadena posterior.", "back", ["hamstrings", "glutes", "forearms"], "barbell"),
  make("back-8", "Peso muerto rumano", "Variante con piernas casi rectas. Enfatiza isquios y glúteos.", "back", ["hamstrings", "glutes"], "barbell"),
  make("back-9", "Hiperextensiones", "Extensión de columna. Fortalece lumbares y glúteos.", "back", ["glutes", "hamstrings"], "bodyweight"),
  make("back-10", "Pullover en polea (straight arm)", "Aislamiento del dorsal con brazos extendidos.", "back", [], "cable"),
  make("back-11", "Jalón con agarre supino", "Variante de jalón. Mayor activación de bíceps.", "back", ["biceps"], "cable"),
  make("back-12", "Remo invertido", "Peso corporal. Tracción horizontal con barra fija baja.", "back", ["biceps"], "bodyweight"),
  make("back-13", "Encogimientos con mancuernas", "Aislamiento de trapecio.", "back", ["forearms"], "dumbbell"),
  make("back-14", "Remo Pendlay", "Remo explosivo desde el suelo en cada repetición.", "back", ["biceps"], "barbell"),
  make("back-15", "Face pulls en polea", "Salud de hombro y trapecio medio. Esencial para postura.", "back", ["shoulders"], "cable"),
  make("back-16", "Remo en máquina con apoyo en pecho", "Tracción guiada sin carga lumbar. Aísla la espalda media.", "back", ["biceps"], "machine"),
  make("back-17", "Jalón a una mano en polea", "Unilateral. Gran estiramiento y contracción del dorsal.", "back", ["biceps"], "cable"),
  make("back-18", "Remo Meadows", "Remo unilateral con barra anclada. Dorsal y espalda alta.", "back", ["biceps", "forearms"], "barbell"),
  make("back-19", "Dominadas con agarre neutro", "Agarre paralelo. Más cómodo para hombros y codos.", "back", ["biceps", "forearms"], "bodyweight"),
  make("back-20", "Remo Yates", "Remo con agarre supino y torso más erguido. Dorsal inferior.", "back", ["biceps"], "barbell"),
  make("back-21", "Dominadas asistidas en máquina", "Dominadas con contrapeso. Ideal para progresar hasta la primera.", "back", ["biceps"], "machine"),

  // SHOULDERS
  make("sh-1", "Press militar de pie", "Press vertical con barra. Movimiento maestro de hombros.", "shoulders", ["triceps"], "barbell"),
  make("sh-2", "Press de hombros con mancuernas", "Press vertical sentado o de pie con mancuernas.", "shoulders", ["triceps"], "dumbbell"),
  make("sh-3", "Press Arnold", "Press con rotación. Trabaja todas las cabezas del deltoides.", "shoulders", ["triceps"], "dumbbell"),
  make("sh-4", "Press en máquina de hombros", "Patrón guiado de press vertical.", "shoulders", ["triceps"], "machine"),
  make("sh-5", "Elevaciones laterales con mancuernas", "Aislamiento del deltoides medio. Crea anchura.", "shoulders", [], "dumbbell"),
  make("sh-6", "Elevaciones laterales en polea", "Tensión constante para deltoides medio.", "shoulders", [], "cable"),
  make("sh-7", "Elevaciones frontales con disco", "Aislamiento del deltoides anterior.", "shoulders", [], "barbell"),
  make("sh-8", "Pájaros (rear delt fly)", "Aislamiento del deltoides posterior con mancuernas.", "shoulders", ["back"], "dumbbell"),
  make("sh-9", "Pájaros en máquina (peck deck inverso)", "Deltoides posterior en máquina.", "shoulders", ["back"], "machine"),
  make("sh-10", "Face pulls", "Salud de hombro. Trapecio medio y deltoides posterior.", "shoulders", ["back"], "cable"),
  make("sh-11", "Press tras nuca", "Press vertical detrás de la cabeza. Solo si tienes movilidad.", "shoulders", ["triceps"], "barbell"),
  make("sh-12", "Remo al mentón", "Trabaja deltoides medio y trapecio.", "shoulders", ["back"], "barbell"),
  make("sh-13", "Elevaciones laterales inclinado", "Mancuernas en banco inclinado lateralmente. Aísla deltoides medio.", "shoulders", [], "dumbbell"),
  make("sh-14", "Press en Smith de hombros", "Press vertical guiado.", "shoulders", ["triceps"], "machine"),
  make("sh-15", "Pike push-ups", "Flexiones en V invertida. Press vertical con peso corporal.", "shoulders", ["triceps"], "bodyweight"),
  make("sh-16", "Press militar sentado con barra", "Press vertical con respaldo. Menos exigencia de core.", "shoulders", ["triceps"], "barbell"),
  make("sh-17", "Elevaciones frontales con mancuernas", "Aislamiento del deltoides anterior, alterno o conjunto.", "shoulders", [], "dumbbell"),
  make("sh-18", "Elevaciones frontales en polea", "Tensión constante en el deltoides anterior.", "shoulders", [], "cable"),
  make("sh-19", "Elevaciones laterales en máquina", "Aislamiento guiado del deltoides medio.", "shoulders", [], "machine"),
  make("sh-20", "Press landmine de hombros", "Press vertical con barra anclada. Amable con el hombro.", "shoulders", ["triceps"], "barbell"),
  make("sh-21", "Pájaros en polea cruzada", "Deltoides posterior con tensión continua.", "shoulders", ["back"], "cable"),

  // BICEPS
  make("bi-1", "Curl con barra", "Curl básico de bíceps. Mucha carga posible.", "biceps", ["forearms"], "barbell"),
  make("bi-2", "Curl con mancuernas alterno", "Curl unilateral. Mejor pico de bíceps.", "biceps", ["forearms"], "dumbbell"),
  make("bi-3", "Curl martillo", "Mancuernas en pronación neutra. Trabaja braquial y antebrazo.", "biceps", ["forearms"], "dumbbell"),
  make("bi-4", "Curl predicador con barra", "Curl en banco scott. Aísla la cabeza corta.", "biceps", [], "barbell"),
  make("bi-5", "Curl con barra Z", "Reduce estrés en muñecas comparado con barra recta.", "biceps", ["forearms"], "barbell"),
  make("bi-6", "Curl en polea baja", "Tensión constante en el bíceps.", "biceps", ["forearms"], "cable"),
  make("bi-7", "Curl concentrado", "Sentado con codo apoyado. Aislamiento extremo.", "biceps", [], "dumbbell"),
  make("bi-8", "Curl inclinado en banco", "Mancuernas en banco a 45°. Estiramiento máximo del bíceps.", "biceps", [], "dumbbell"),
  make("bi-9", "Curl 21s", "7 reps medio inferior + 7 medio superior + 7 completas. Brutal.", "biceps", [], "barbell"),
  make("bi-10", "Curl en polea con cuerda", "Curl martillo con cuerda. Trabaja braquiorradial.", "biceps", ["forearms"], "cable"),
  make("bi-11", "Curl Spider", "Tumbado boca abajo en banco inclinado. Aísla bíceps.", "biceps", [], "dumbbell"),
  make("bi-12", "Chin-ups (dominadas supinas)", "Tracción vertical agarre supino. Mucho bíceps.", "biceps", ["back"], "bodyweight"),
  make("bi-13", "Curl en máquina", "Patrón guiado de curl. Bueno para aislamiento.", "biceps", [], "machine"),
  make("bi-14", "Curl Zottman", "Curl supino subiendo, pronación arriba, baja prono. Bíceps + antebrazo.", "biceps", ["forearms"], "dumbbell"),
  make("bi-15", "Curl invertido (pronado)", "Curl con barra en pronación. Trabaja braquial y antebrazo.", "biceps", ["forearms"], "barbell"),
  make("bi-16", "Curl predicador con mancuerna", "Unilateral en banco scott. Aísla el bíceps sin impulso.", "biceps", [], "dumbbell"),
  make("bi-17", "Curl en polea alta (doble bíceps)", "Brazos en cruz con poleas altas. Contracción máxima.", "biceps", [], "cable"),
  make("bi-18", "Curl martillo cruzado", "Mancuerna hacia el hombro contrario. Braquial y braquiorradial.", "biceps", ["forearms"], "dumbbell"),
  make("bi-19", "Curl con mancuernas sentado", "Sentado con respaldo. Reduce el balanceo del cuerpo.", "biceps", ["forearms"], "dumbbell"),
  make("bi-20", "Curl Bayesian en polea", "De espaldas a la polea. Mucho estiramiento del bíceps.", "biceps", [], "cable"),
  make("bi-21", "Curl con barra agarre ancho", "Agarre ancho. Mayor énfasis en la cabeza corta.", "biceps", ["forearms"], "barbell"),

  // TRICEPS
  make("tri-1", "Press francés con barra", "Extensión de tríceps tumbado. Trabaja la cabeza larga.", "triceps", [], "barbell"),
  make("tri-2", "Extensión de tríceps en polea (cuerda)", "Tríceps en polea alta con cuerda. Tensión constante.", "triceps", [], "cable"),
  make("tri-3", "Extensión de tríceps en polea (barra)", "Pushdown clásico con barra recta o V.", "triceps", [], "cable"),
  make("tri-4", "Press cerrado con barra", "Press de banca con agarre estrecho. Tríceps + pecho interno.", "triceps", ["chest", "shoulders"], "barbell"),
  make("tri-5", "Fondos en paralelas (verticales)", "Peso corporal. Erguido para enfatizar tríceps.", "triceps", ["chest"], "bodyweight"),
  make("tri-6", "Fondos en banco", "Manos en banco detrás. Buen ejercicio de calentamiento.", "triceps", [], "bodyweight"),
  make("tri-7", "Extensión por encima de la cabeza con mancuerna", "Estira la cabeza larga del tríceps.", "triceps", [], "dumbbell"),
  make("tri-8", "Extensión por encima cabeza en polea (cuerda)", "Cuerda detrás de la cabeza. Cabeza larga del tríceps.", "triceps", [], "cable"),
  make("tri-9", "Patada de tríceps con mancuerna", "Aislamiento de tríceps inclinado hacia adelante.", "triceps", [], "dumbbell"),
  make("tri-10", "Patada de tríceps en polea", "Polea baja. Tensión constante en el tríceps.", "triceps", [], "cable"),
  make("tri-11", "Press JM", "Híbrido entre press francés y press cerrado. Muy efectivo.", "triceps", ["chest"], "barbell"),
  make("tri-12", "Diamond push-ups", "Flexiones con manos juntas. Tríceps con peso corporal.", "triceps", ["chest"], "bodyweight"),
  make("tri-13", "Extensión en máquina de tríceps", "Patrón de pushdown guiado.", "triceps", [], "machine"),
  make("tri-14", "Press francés con mancuernas", "Variante con mancuernas. Más rango de movimiento.", "triceps", [], "dumbbell"),
  make("tri-15", "Skullcrushers con barra Z", "Extensión inclinada hacia la frente. Cuidado con codos.", "triceps", [], "barbell"),
  make("tri-16", "Press cerrado en Smith", "Press de agarre estrecho guiado. Tríceps y pecho interno.", "triceps", ["chest", "shoulders"], "machine"),
  make("tri-17", "Extensión de tríceps a una mano en polea", "Unilateral. Corrige asimetrías entre brazos.", "triceps", [], "cable"),
  make("tri-18", "Extensión de tríceps agarre inverso", "Pushdown con agarre supino. Cabeza medial.", "triceps", [], "cable"),
  make("tri-19", "Press francés en polea", "Tumbado con polea baja. Tensión constante en el tríceps.", "triceps", [], "cable"),
  make("tri-20", "Fondos asistidos en máquina", "Fondos con contrapeso. Progresión hacia el peso corporal.", "triceps", ["chest"], "machine"),
  make("tri-21", "Press cerrado con mancuernas", "Mancuernas juntas. Tríceps con buen rango de movimiento.", "triceps", ["chest", "shoulders"], "dumbbell"),

  // QUADRICEPS
  make("q-1", "Sentadilla con barra", "Reina de los ejercicios de pierna. Trabaja todo el tren inferior.", "quadriceps", ["glutes", "hamstrings"], "barbell"),
  make("q-2", "Sentadilla frontal", "Barra al frente. Mayor énfasis en cuádriceps.", "quadriceps", ["glutes"], "barbell"),
  make("q-3", "Prensa de piernas", "Máquina inclinada. Mucha carga posible. Seguro.", "quadriceps", ["glutes"], "machine"),
  make("q-4", "Hack squat", "Sentadilla en máquina hack. Aísla cuádriceps.", "quadriceps", ["glutes"], "machine"),
  make("q-5", "Extensiones de cuádriceps", "Aislamiento puro de cuádriceps en máquina.", "quadriceps", [], "machine"),
  make("q-6", "Zancadas (lunges) con mancuernas", "Trabajo unilateral. Equilibrio y fuerza.", "quadriceps", ["glutes"], "dumbbell"),
  make("q-7", "Zancadas búlgaras", "Pie trasero elevado. Brutal para cuádriceps y glúteos.", "quadriceps", ["glutes"], "dumbbell"),
  make("q-8", "Sentadilla goblet", "Mancuerna pegada al pecho. Excelente técnica.", "quadriceps", ["glutes"], "dumbbell"),
  make("q-9", "Step-ups con mancuernas", "Subir a un cajón. Gran trabajo unilateral.", "quadriceps", ["glutes"], "dumbbell"),
  make("q-10", "Sentadilla en Smith", "Sentadilla guiada. Ideal para enfocar cuádriceps.", "quadriceps", ["glutes"], "machine"),
  make("q-11", "Sentadilla sissy", "Sentadilla extrema con apoyo. Aísla cuádriceps.", "quadriceps", [], "bodyweight"),
  make("q-12", "Zancadas caminando", "Zancadas en movimiento. Trabaja equilibrio.", "quadriceps", ["glutes"], "barbell"),
  make("q-13", "Sentadilla pausada", "3 segundos en el fondo. Construye fuerza desde el hoyo.", "quadriceps", ["glutes"], "barbell"),
  make("q-14", "Prensa unilateral", "Una pierna a la vez en prensa. Corrige asimetrías.", "quadriceps", ["glutes"], "machine"),
  make("q-15", "Sentadilla con cinturón (belt squat)", "Carga sin comprimir columna.", "quadriceps", ["glutes"], "machine"),
  make("q-16", "Sentadilla Zercher", "Barra en el pliegue de los codos. Cuádriceps y core.", "quadriceps", ["glutes", "back"], "barbell"),
  make("q-17", "Sentadilla con salto", "Pliométrico. Potencia explosiva de piernas.", "quadriceps", ["glutes", "calves"], "bodyweight"),
  make("q-18", "Sentadilla con peso corporal", "Base técnica. Ideal para calentar o para volumen alto.", "quadriceps", ["glutes"], "bodyweight"),
  make("q-19", "Extensión de cuádriceps unilateral", "Una pierna a la vez en máquina. Corrige asimetrías.", "quadriceps", [], "machine"),
  make("q-20", "Sentadilla en cajón (box squat)", "Sentarse sobre un cajón. Control y fuerza desde abajo.", "quadriceps", ["glutes", "hamstrings"], "barbell"),
  make("q-21", "Prensa de piernas horizontal", "Prensa con respaldo vertical. Cuádriceps con menos carga lumbar.", "quadriceps", ["glutes"], "machine"),

  // HAMSTRINGS
  make("h-1", "Peso muerto rumano (RDL)", "Bisagra de cadera. Rey de los isquios.", "hamstrings", ["glutes", "back"], "barbell"),
  make("h-2", "Curl femoral acostado", "Aislamiento de isquios en máquina tumbado.", "hamstrings", [], "machine"),
  make("h-3", "Curl femoral sentado", "Aislamiento de isquios en máquina sentado.", "hamstrings", [], "machine"),
  make("h-4", "Peso muerto rumano con mancuernas", "Variante con mancuernas. Más rango.", "hamstrings", ["glutes"], "dumbbell"),
  make("h-5", "Peso muerto a una pierna", "Unilateral. Equilibrio + fuerza de isquios.", "hamstrings", ["glutes"], "dumbbell"),
  make("h-6", "Buenos días (good mornings)", "Bisagra de cadera con barra en espalda.", "hamstrings", ["glutes", "back"], "barbell"),
  make("h-7", "Curl nórdico", "Curl femoral con peso corporal. Brutal excéntrico.", "hamstrings", [], "bodyweight"),
  make("h-8", "Glute-ham raise (GHR)", "Banco específico. Trabajo masivo de isquios.", "hamstrings", ["glutes"], "bodyweight"),
  make("h-9", "Peso muerto sumo", "Stance ancho. Más glúteos e isquios.", "hamstrings", ["glutes", "back"], "barbell"),
  make("h-10", "Hip thrust", "Empuje de cadera con barra. Glúteos e isquios.", "hamstrings", ["glutes"], "barbell"),
  make("h-11", "Curl femoral de pie en polea", "Curl unilateral en polea baja.", "hamstrings", [], "cable"),
  make("h-12", "Peso muerto con piernas rígidas", "Similar a RDL pero piernas más rectas.", "hamstrings", ["glutes"], "barbell"),
  make("h-13", "Reverse hyper", "Aislamiento de isquios y glúteos. Salud lumbar.", "hamstrings", ["glutes"], "machine"),
  make("h-14", "Slider hamstring curl", "Curl con discos en suelo. Peso corporal.", "hamstrings", ["glutes"], "bodyweight"),
  make("h-15", "Peso muerto trap bar", "Híbrido entre sentadilla y peso muerto.", "hamstrings", ["glutes", "quadriceps"], "barbell"),
  make("h-16", "Curl femoral unilateral en máquina", "Una pierna a la vez. Aislamiento y simetría.", "hamstrings", [], "machine"),
  make("h-17", "Curl femoral con balón suizo", "Talones sobre el balón. Isquios y estabilidad.", "hamstrings", ["glutes"], "bodyweight"),
  make("h-18", "Puente de glúteo con pies elevados", "Pies sobre banco. Mayor trabajo de isquios.", "hamstrings", ["glutes"], "bodyweight"),
  make("h-19", "Buenos días sentado", "Bisagra de cadera sentado. Isquios y espalda baja.", "hamstrings", ["glutes", "back"], "barbell"),
  make("h-20", "Peso muerto rumano en Smith", "Bisagra guiada. Permite concentrarse en el estiramiento.", "hamstrings", ["glutes"], "machine"),
  make("h-21", "Curl femoral con mancuerna", "Tumbado boca abajo con mancuerna entre los pies.", "hamstrings", [], "dumbbell"),

  // GLUTES
  make("g-1", "Hip thrust con barra", "Rey de los glúteos. Empuje de cadera apoyado.", "glutes", ["hamstrings"], "barbell"),
  make("g-2", "Sentadilla búlgara", "Pie trasero elevado. Brutal para glúteos.", "glutes", ["quadriceps"], "dumbbell"),
  make("g-3", "Patada de glúteo en polea", "Aislamiento puro de glúteo.", "glutes", [], "cable"),
  make("g-4", "Abducción en máquina", "Aductión de cadera para glúteo medio.", "glutes", [], "machine"),
  make("g-5", "Glute bridge con barra", "Variante de hip thrust desde el suelo.", "glutes", ["hamstrings"], "barbell"),
  make("g-6", "Sentadilla sumo", "Stance ancho. Énfasis en aductores y glúteos.", "glutes", ["quadriceps"], "barbell"),
  make("g-7", "Step-ups altos", "Subidas a cajón alto. Glúteo y cuádriceps.", "glutes", ["quadriceps"], "dumbbell"),
  make("g-8", "Patada con banda", "Trabajo unilateral con banda elástica.", "glutes", [], "bodyweight"),
  make("g-9", "Hip thrust unilateral", "Una pierna a la vez. Asimetrías.", "glutes", ["hamstrings"], "barbell"),
  make("g-10", "Cable kickback", "Patada hacia atrás en polea.", "glutes", [], "cable"),
  make("g-11", "Frog pump", "Pump de glúteos con piernas en posición rana.", "glutes", [], "bodyweight"),
  make("g-12", "Squat búlgaro Smith", "Búlgara guiada en máquina Smith.", "glutes", ["quadriceps"], "machine"),
  make("g-13", "Cable pull-through", "Tracción entre piernas con polea baja.", "glutes", ["hamstrings"], "cable"),
  make("g-14", "Reverse lunge", "Zancada hacia atrás. Más glúteo que zancada normal.", "glutes", ["quadriceps"], "dumbbell"),
  make("g-15", "Curtsy lunge", "Zancada lateral cruzada. Glúteo medio.", "glutes", ["quadriceps"], "dumbbell"),
  make("g-16", "Hip thrust en máquina", "Empuje de cadera guiado. Cómodo con mucha carga.", "glutes", ["hamstrings"], "machine"),
  make("g-17", "Hip thrust con mancuerna", "Mancuerna sobre la cadera. Buen punto de partida.", "glutes", ["hamstrings"], "dumbbell"),
  make("g-18", "Abducción de cadera en polea", "De pie con tobillera. Glúteo medio.", "glutes", [], "cable"),
  make("g-19", "Clamshell con banda", "Tumbado de lado abriendo la rodilla. Glúteo medio.", "glutes", [], "bodyweight"),
  make("g-20", "Donkey kick", "A cuatro apoyos, patada hacia arriba. Aislamiento del glúteo.", "glutes", ["hamstrings"], "bodyweight"),
  make("g-21", "Sentadilla en Smith con pies adelantados", "Pies adelantados en máquina. Mayor énfasis en glúteo.", "glutes", ["quadriceps", "hamstrings"], "machine"),

  // CALVES
  make("ca-1", "Elevación de talones de pie", "Gemelos en máquina de pie. Carga máxima.", "calves", [], "machine"),
  make("ca-2", "Elevación de talones sentado", "Sóleo aislado al estar sentado.", "calves", [], "machine"),
  make("ca-3", "Elevación de talones en prensa", "Gemelos en prensa de piernas.", "calves", [], "machine"),
  make("ca-4", "Donkey calf raise", "Inclinado hacia adelante. Gemelos clásico.", "calves", [], "machine"),
  make("ca-5", "Elevación con mancuerna a una pierna", "Unilateral. Mucho rango.", "calves", [], "dumbbell"),
  make("ca-6", "Saltos a cajón", "Pliométrico para potencia y gemelos.", "calves", [], "bodyweight"),
  make("ca-7", "Elevación con barra en hombros", "Versión casera con barra.", "calves", [], "barbell"),
  make("ca-8", "Elevación en escalón", "Peso corporal con mucho rango.", "calves", [], "bodyweight"),
  make("ca-9", "Calf raise en Smith", "Guiado. Permite enfocarse en contracción.", "calves", [], "machine"),
  make("ca-10", "Elevación con mancuernas de pie", "Variante con mancuernas.", "calves", [], "dumbbell"),
  make("ca-11", "Sled push", "Empujar trineo. Trabajo de gemelos pliométrico.", "calves", ["quadriceps"], "machine"),
  make("ca-12", "Saltos a la comba", "Excelente acondicionamiento + gemelos.", "calves", [], "bodyweight"),
  make("ca-13", "Elevación en hack squat", "Gemelos en máquina hack squat.", "calves", [], "machine"),
  make("ca-14", "Tibial raise", "Elevación de punta. Trabaja tibial anterior.", "calves", [], "bodyweight"),
  make("ca-15", "Farmer walk en puntillas", "Caminar con peso en puntas.", "calves", ["forearms"], "dumbbell"),
  make("ca-16", "Elevación de talones sentado con mancuerna", "Mancuerna sobre las rodillas. Trabaja el sóleo.", "calves", [], "dumbbell"),
  make("ca-17", "Saltos de tobillo (pogo jumps)", "Saltos cortos y rápidos. Rigidez y potencia de tobillo.", "calves", [], "bodyweight"),
  make("ca-18", "Elevación de talones en prensa a una pierna", "Unilateral en prensa. Corrige asimetrías.", "calves", [], "machine"),
  make("ca-19", "Caminata en puntillas", "Caminar sobre las puntas. Resistencia de gemelos.", "calves", [], "bodyweight"),
  make("ca-20", "Elevación de talones a una pierna en máquina", "Unilateral en máquina de pie. Gran contracción.", "calves", [], "machine"),
  make("ca-21", "Elevación de talones con banda elástica", "Banda bajo el pie. Resistencia progresiva.", "calves", [], "bodyweight"),

  // ABS
  make("ab-1", "Crunch abdominal", "Crunch básico en suelo. Recto abdominal.", "abs", [], "bodyweight"),
  make("ab-2", "Plancha (plank)", "Isométrico. Core entero.", "abs", [], "bodyweight"),
  make("ab-3", "Elevación de piernas colgado", "Suspendido en barra. Abdomen inferior.", "abs", [], "bodyweight"),
  make("ab-4", "Rueda abdominal (ab wheel)", "Rollout con rueda. Brutal para abs.", "abs", [], "bodyweight"),
  make("ab-5", "Crunch en polea (cable crunch)", "Arrodillado con cuerda en polea alta.", "abs", [], "cable"),
  make("ab-6", "Russian twist", "Rotación de tronco con peso. Oblicuos.", "abs", [], "dumbbell"),
  make("ab-7", "Mountain climbers", "Cardio + core. Dinámico.", "abs", [], "bodyweight"),
  make("ab-8", "Crunch inverso", "Llevar caderas hacia el pecho. Abdomen inferior.", "abs", [], "bodyweight"),
  make("ab-9", "Hanging knee raises", "Elevación de rodillas colgado.", "abs", [], "bodyweight"),
  make("ab-10", "Plancha lateral", "Isométrico de oblicuos.", "abs", [], "bodyweight"),
  make("ab-11", "Sit-ups con peso", "Crunch completo con disco en pecho.", "abs", [], "bodyweight"),
  make("ab-12", "Dragon flag", "Movimiento avanzado de Bruce Lee. Core completo.", "abs", [], "bodyweight"),
  make("ab-13", "Pallof press", "Anti-rotación con polea o banda.", "abs", [], "cable"),
  make("ab-14", "Wood chopper en polea", "Movimiento diagonal. Oblicuos potentes.", "abs", [], "cable"),
  make("ab-15", "Toes to bar", "Levantar puntas hasta la barra colgado. Abs avanzado.", "abs", [], "bodyweight"),
  make("ab-16", "Crunch bicicleta", "Codo a rodilla contraria. Recto abdominal y oblicuos.", "abs", [], "bodyweight"),
  make("ab-17", "Elevación de piernas en banco", "Tumbado en banco. Abdomen inferior sin colgarse.", "abs", [], "bodyweight"),
  make("ab-18", "Crunch en máquina", "Patrón guiado con carga progresiva.", "abs", [], "machine"),
  make("ab-19", "Hollow body hold", "Isométrico con lumbar pegada al suelo. Core profundo.", "abs", [], "bodyweight"),
  make("ab-20", "V-ups", "Manos y pies se encuentran arriba. Abdomen completo.", "abs", [], "bodyweight"),
  make("ab-21", "Plancha con toque de hombro", "Plancha alta alternando toques. Anti-rotación.", "abs", [], "bodyweight"),

  // FOREARMS
  make("fa-1", "Curl de muñeca con barra", "Flexión de muñeca con barra. Antebrazo flexor.", "forearms", [], "barbell"),
  make("fa-2", "Curl invertido de muñeca", "Extensión de muñeca con barra. Antebrazo extensor.", "forearms", [], "barbell"),
  make("fa-3", "Farmer walk", "Caminar con mancuernas pesadas. Agarre.", "forearms", [], "dumbbell"),
  make("fa-4", "Curl martillo para antebrazo", "Mancuernas neutras. Bíceps + antebrazo.", "forearms", ["biceps"], "dumbbell"),
  make("fa-5", "Plate pinch", "Sostener disco entre dedos.", "forearms", [], "bodyweight"),
  make("fa-6", "Curl Zottman para antebrazo", "Curl con rotación. Trabaja todo el antebrazo.", "forearms", ["biceps"], "dumbbell"),
  make("fa-7", "Wrist roller", "Enrollar peso colgado de palo. Antebrazos masivos.", "forearms", [], "bodyweight"),
  make("fa-8", "Reverse curl con barra", "Curl pronado. Braquiorradial y extensores.", "forearms", ["biceps"], "barbell"),
  make("fa-9", "Dead hang", "Colgarse de la barra. Resistencia de agarre.", "forearms", [], "bodyweight"),
  make("fa-10", "Behind-the-back wrist curl", "Curl de muñeca tras espalda con barra.", "forearms", [], "barbell"),
  make("fa-11", "Captains of crush (gripper)", "Pinza de agarre. Fuerza explosiva.", "forearms", [], "bodyweight"),
  make("fa-12", "Towel pull-ups", "Dominadas con toalla. Agarre brutal.", "forearms", ["back"], "bodyweight"),
  make("fa-13", "Cable wrist curl", "Curl de muñeca en polea baja.", "forearms", [], "cable"),
  make("fa-14", "Finger curl con barra", "Rodar barra desde dedos. Flexores profundos.", "forearms", [], "barbell"),
  make("fa-15", "Rack hold (heavy)", "Sostener barra pesada en jaula. Agarre estático.", "forearms", [], "barbell"),
  make("fa-16", "Farmer walk con trap bar", "Caminar con barra hexagonal pesada. Agarre y trapecio.", "forearms", [], "barbell"),
  make("fa-17", "Suitcase carry", "Caminar con una mancuerna. Agarre y oblicuos.", "forearms", ["abs"], "dumbbell"),
  make("fa-18", "Curl de muñeca con mancuerna", "Flexión de muñeca unilateral. Antebrazo flexor.", "forearms", [], "dumbbell"),
  make("fa-19", "Extensión de muñeca con mancuerna", "Extensión de muñeca unilateral. Antebrazo extensor.", "forearms", [], "dumbbell"),
  make("fa-20", "Pronación y supinación con mancuerna", "Rotar el antebrazo con peso. Salud de codo y muñeca.", "forearms", [], "dumbbell"),
  make("fa-21", "Dead hang a una mano", "Colgarse de un solo brazo. Agarre avanzado.", "forearms", ["back"], "bodyweight"),
];

export const MUSCLE_GROUP_LABELS: Record<string, string> = {
  chest: "Pecho",
  back: "Espalda",
  shoulders: "Hombros",
  biceps: "Bíceps",
  triceps: "Tríceps",
  quadriceps: "Cuádriceps",
  hamstrings: "Isquiotibiales",
  glutes: "Glúteos",
  calves: "Gemelos",
  abs: "Abdominales",
  forearms: "Antebrazos",
};

export const MUSCLE_GROUPS: Array<keyof typeof MUSCLE_GROUP_LABELS> = [
  "chest",
  "back",
  "shoulders",
  "biceps",
  "triceps",
  "quadriceps",
  "hamstrings",
  "glutes",
  "calves",
  "abs",
  "forearms",
];

export const EXERCISE_TYPE_LABELS: Record<string, string> = {
  barbell: "Barra",
  dumbbell: "Mancuernas",
  machine: "Máquina",
  cable: "Cable / Polea",
  bodyweight: "Peso corporal",
};

export function getExerciseById(id: string, customExercises: Exercise[] = []): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id) ?? customExercises.find((e) => e.id === id);
}
