import { migrate } from "drizzle-orm/expo-sqlite/migrator";

import type { DB } from "./client/sqlite";
// `migrations.js` is generated by `drizzle-kit generate` for the `expo`
// driver. It bundles the SQL files + journal so the migrator can apply them
// in order at app boot. The `.sql` imports inside that file are inlined at
// build time by `babel-plugin-inline-import` (configured in
// `artifacts/ironlog/babel.config.js`).
import migrations from "./migrations/sqlite/migrations";

/**
 * Apply pending Drizzle migrations against the given DB.
 *
 * Called once from `bootDatabase()` at app start (cf. DDB-19 — fail-fast on
 * error so the user's DB is never silently destroyed). Drizzle-kit only
 * supports forward migrations (no `down`), and migrations are additive only.
 */
export async function runMigrations(db: DB): Promise<void> {
  await migrate(db, migrations);
}
